# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

networks:
  dev:
    driver: bridge

services:
  seesharpapi:
    image: seesharpapi
    build:
      context: .
      dockerfile: src/SeeSharp.Api/Dockerfile
    ports:
      - 7777:7777
    depends_on:
      - sql_server_blog
    networks:
      - dev
    environment:
      - ASPNETCORE_URLS=http://+:7777

  sql_server_blog:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server_blog
    ports:
      - '1432:1432'
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=P@ssw0rd
    networks:
      - dev
